# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZMA5nsl73zpCYYOX9nmHC2gQEE-qxn3d
"""

import io
import base64
import torch
import numpy as np
from flask import Flask, request, jsonify
from flask_cors import CORS
from PIL import Image
from transformers import OneFormerProcessor, OneFormerForUniversalSegmentation

app = Flask(__name__)
CORS(app) # This allows your website to talk to this backend

# --- INITIALIZATION (Runs only once when server starts) ---
DEVICE = "cpu" # PythonAnywhere free tier does not have GPUs

MODEL_ID = "shi-labs/oneformer_coco_swin_tiny"

print("Loading model... please wait.")
processor = OneFormerProcessor.from_pretrained(MODEL_ID)
model = OneFormerForUniversalSegmentation.from_pretrained(MODEL_ID).to(DEVICE)
model.eval()
print("Model loaded and ready!")

@app.route('/segment', methods=['POST'])
def segment_image():
    # 1. Get the image from the request
    if 'image' not in request.files:
        return jsonify({"error": "No image provided"}), 400

    file = request.files['image']
    image = Image.open(file.stream).convert("RGB")

    # 2. Run AI Inference (already loaded in memory)
    with torch.no_grad():
        inputs = processor(images=image, task_inputs=["panoptic"], return_tensors="pt")
        inputs = {k: v.to(DEVICE) for k, v in inputs.items()}
        outputs = model(**inputs)

    panoptic = processor.post_process_panoptic_segmentation(outputs, target_sizes=[image.size[::-1]])[0]

    # 3. Generate the report (Logic from your Step 6)
    segments_info = panoptic["segments_info"]
    id2label = model.config.id2label

    report = []
    for seg in segments_info:
        label_name = id2label.get(seg.get("label_id"), "unknown")
        report.append({
            "label": label_name,
            "id": seg["id"],
            "score": float(seg.get("score", 0))
        })

    return jsonify({
        "status": "success",
        "segments": report
    })

if __name__ == '__main__':
    app.run()